### PR TITLE
Primarily, fix memory leak causing production downtime.

### PR DESCRIPTION
**Pull request by UnbounDev**
Major implementation changes are in this commit: 4b76b31d08b523cd03efc48abd8087a149429c6c

### CODE REVIEW

**Comment by jimaek** [comment]
@UnbounDev Can you make sure that neither api-sync or api will go down in case a source goes down?

If cdnjs or any other source goes down then we get an email but the API continue to function. So we still need to update the frontend part. The master branch doesnt have the temp that I deployed live to fix it.

Also next step will be to move away from api.cdnjs.com and pull the data the same way we do for jsDelivr.

**Comment by jimaek** [comment]
Can you also please make sure webhooks work as intended? 

Maybe when you receive a webhook and process it successfully then write to logentries to make it easier to debug? Like "Webhook for jsDelivr recieved" "Starting to update jsDelivr"...

**Comment by UnbounDev** [comment]
Additional logging has been added for webhooks and a PR submitted (#24)

You can very easily test the webhooks by editing the jsdelivr README and committing to the master branch, this will trigger a webhook which you should then see in the logs.

**Comment by jimaek** [comment]
Awesome, thank you. Please add the other tasks to Trello to make sure we dont forget

**Comment by UnbounDev** [comment]
Done and done! 

Api-sync already stops attempting to update data if an error is thrown (and we now throw one when cdnjs sync comes back w/ improper data, see 4b76b31), this means that the front-end *should* simply continue referencing stale content.

**Comment by jimaek** [comment]
But what happens if the frontend doesnt have any stale content? I believe it will continue failing to start with errors like "Failed to open cdnjs.json" 
At least thats what was happening before I removed cdnjs from the settings completely.

**Comment by UnbounDev** [comment]
I honestly don't know (haven't looked at the front-end code in depth) - it *ought* to handle those errors gracefully but if we're seeing that error then it must not be, I'll give the api front end a glace when I have a chance.

**Pull request merged**
