### PR TITLE
Patch/local git/etags

### PR DESCRIPTION
**Pull request by UnbounDev**
Infers eTags from the git sha values.

@megawac got :eyes: on this?

### CODE REVIEW

**Comment by megawac** [comment]
I was going to suggest just using https://github.com/jshttp/etag to create an etag based on the file contents

`etag( projectConfig )`

**Comment by UnbounDev** [comment]
A simpler sol'n, but it would have a high computation cost (the tag would
have to be generated at every sync since local-git doesn't allow for
partial sync cycles), go ahead and change it if you like! All I care about
is a stable way to maintain an etag list consistent w/ the project version.

**Comment by megawac** [comment]
It would be simpler and avoid a fs.readFile/writeFile for the etags for the
non etag hit case. Plus computing etag sums are relatively cheap. I'll make
a patch when I get some free time, feel free to merge if this works

**Comment by jimaek** [comment]
Right now all i want is to get the API working. Once its back to normal you both can apply as many fixes and improvements as you wish to make it faster, smarter and more stable.

**Pull request merged**
