### PR TITLE
Fix semver sorting algorithm

### PR DESCRIPTION
**Pull request by megawac**
Fixes jsdelivr/api#104

Should revert https://github.com/jsdelivr/api/pull/105

### CODE REVIEW

**Comment by jimaek** [comment]
It will work 100% like the current implementation? Dont want to break anything

**Comment by megawac** [comment]
It will work like the existing solution but won't error with non semver
complaint versioning (e.g `1.2`, `BETA1`, etc)

**Comment by jimaek** [comment]
It doesnt work

```
12cfa10f-70f0-40cf-b85e-acc00ba18a67 2015-10-12T16:21:20.678Z info running task... google {"minute":3}

12cfa10f-70f0-40cf-b85e-acc00ba18a67 2015-10-12T16:21:20.783Z info Starting to update google data

12cfa10f-70f0-40cf-b85e-acc00ba18a67 2015-10-12T16:21:21.277Z info Fetched google data

12cfa10f-70f0-40cf-b85e-acc00ba18a67 2015-10-12T16:21:21.346Z info google etags saved to /home/api-sync/data/google.json

12cfa10f-70f0-40cf-b85e-acc00ba18a67 2015-10-12T16:21:21.350Z info Node server stopped.

/home/api-sync/node_modules/semvish/node_modules/semver/semver.js:281
    throw new TypeError('Invalid Version: ' + version);
          ^
TypeError: Invalid Version: null
    at new SemVer (/home/api-sync/node_modules/semvish/node_modules/semver/semver.js:281:11)
    at SemVer.SemVish (/home/api-sync/node_modules/semvish/index.js:36:24)
    at SemVish (/home/api-sync/node_modules/semvish/index.js:35:40)
    at SemVish.(anonymous function) (/home/api-sync/node_modules/semvish/index.js:58:29)
    at Array.sort (native)
    at module.exports (/home/api-sync/lib/sort_versions.js:11:24)
    at /home/api-sync/tasks/task.js:29:28
    at Array.map (native)
    at /home/api-sync/tasks/task.js:28:29
    at /home/api-sync/tasks/google.js:42:9

```

**Comment by jimaek** [comment]
We need more checks to make sure this wont happen again. Travis should have picked this up.
@megawac Can you create a new task for this?

**Comment by megawac** [comment]
Shoot, I only tested it with two libraries: one using a semver versioning
scheme and one not. I'm not sure where that null came from

**Comment by megawac** [comment]
I found the issue: api-sync malicously identifies one of google cdn's
angularjs versions as `'1.0.1 1.4.2-rc.2'` which semvish fails to parse.
See http://api.jsdelivr.com/v1/google/libraries?name=angularjs

```

{
        "version": "1.0.1  1.4.0-rc.2",
        "files": [
          "angular.js",
          "angular.min.js"
        ]
}

```

**Comment by megawac** [comment]
Fixed in https://github.com/jsdelivr/api-sync/commit/5835f5dc67c581ed706b5d297ae4a101b0dbb7ff

**Comment by megawac** [comment]
To get travis to be able to test api-sync we would need to generate some github tokens so it could scrape bootstrap cdn

**Comment by jimaek** [comment]
Everything seems to be back to normal. Thank you

**Comment by jimaek** [comment]
@megawac  It still breaks

```

12cfa10f-70f0-40cf-b85e-acc00ba18a67 2015-10-12T18:07:56.074Z info Pulling changes for the cdnjs repo...

12cfa10f-70f0-40cf-b85e-acc00ba18a67 2015-10-12T18:08:05.649Z info Done pull...

12cfa10f-70f0-40cf-b85e-acc00ba18a67 2015-10-12T18:08:33.681Z info Node server stopped.

/home/api-sync/node_modules/semvish/node_modules/semver/semver.js:281
    throw new TypeError('Invalid Version: ' + version);
          ^
TypeError: Invalid Version: null
    at new SemVer (/home/api-sync/node_modules/semvish/node_modules/semver/semver.js:281:11)
    at SemVer.SemVish (/home/api-sync/node_modules/semvish/index.js:36:24)
    at SemVish (/home/api-sync/node_modules/semvish/index.js:35:40)
    at SemVish.(anonymous function) (/home/api-sync/node_modules/semvish/index.js:58:29)
    at Array.sort (native)
    at module.exports (/home/api-sync/lib/sort_versions.js:11:38)
    at /home/api-sync/tasks/task.js:29:28
    at Array.map (native)
    at /home/api-sync/tasks/task.js:28:29
    at /home/api-sync/tasks/cdnjs.js:79:5

```

**Comment by jimaek** [comment]
I reverted to the old code again. Please fix all possible bugs, not sure why but the previous code worked fine with all the versions. Maybe apply some of the same logic?

**Pull request merged**
